name: cornsjobs

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *' # every 5 minutes
  # push:
  #   branches:
  #     - main

jobs:
  cornsjobs-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First Step
        run: |
          echo "ami corn job theke bolsi go"
