name: dependance job

on:
  workflow_dispatch:

jobs:
  first-multi-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: first steps
        run: |
          echo "ami first step from multijobs one"

  second-multi-jobs:
    runs-on: ubuntu-latest
    needs: [first-multi-jobs]

    steps:
      - name: second steps
        run: |
          echo "ami second step from multijobs one"
