name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Say Hello
        run: echo "Hello, world!"
      - name: Say Goodbye
        run: echo "Goodbye, world!"
